CC = gcc  # C compiler
CFLAGS = -fPIC -Wall  # C flags
LDFLAGS = -shared   # linking flags
EXEFLAGS = -L. -ltttb
RM = rm -f   # rm command
TARGET_LIB = libtttb.so  # target lib
EXECUTABLE = ttt
SRCS = board.c main.c
OBJS = $(SRCS:.c=.o)

all: $(TARGET_LIB) $(EXECUTABLE)

$(TARGET_LIB): $(OBJS)
	$(CC) ${LDFLAGS} -o $@ $^

$(EXECUTABLE): main.o $(LIBRARY)
	$(CC) -o $@ $< $(EXEFLAGS)

clean:
	-${RM} ${TARGET_LIB} ${OBJS} $(EXECUTABLE)