CC = gcc
CFLAGS = -Wall

all: exemplul1 exemplul2 exemplul3

exemplul1: exemplul1.c
	$(CC) $(CFLAGS) -o $@ $< $(LIBS)

exemplul2: exemplul2.c
	$(CC) $(CFLAGS) -o $@ $< $(LIBS)

exemplul3: exemplul3.c
	$(CC) $(CFLAGS) -o $@ $< $(LIBS)

clean:
	rm -f exemplul1 exemplul2 exemplul3
